---
title: "simulation"
author: "Joe Despres"
date: "9/27/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidymodels)
library(lubridate)
library(tictoc)
library(patchwork)
hotels <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-11/hotels.csv')
theme_set(theme_light())


hotels %>% 
  group_by(customer_type) %>% 
  count(is_canceled)
```

```{r}
hotels <- hotels %>% 
    mutate(
    check_in_date = ymd(paste(arrival_date_year, arrival_date_month,
                                      arrival_date_day_of_month)),
    reservation_date = check_in_date, 
    booking_date = check_in_date - days(lead_time),
         stay_length = stays_in_week_nights + stays_in_weekend_nights,
         check_out_date = if_else(reservation_status != "No-Show",
                                  reservation_date + days(stay_length), ymd("NA"))) %>% 
  select(booking_date, is_canceled, hotel,customer_type, adults, children, babies, lead_time, stay_length, deposit_type, check_in_date, check_out_date) %>% 
  mutate(not_canceled = (is_canceled - 1) * -1,
       deposit = if_else(deposit_type == "Refundable" | 
                                deposit_type == "Non Refund", "Deposit", "No Deposit"))

```

```{r}
city_hotel <- hotels %>% 
  filter(hotel == "City Hotel")

training_dates <- city_hotel %>% 
  count(check_in_date) %>% 
  arrange(check_in_date) %>% 
  slice(round(0.8*n()):n()) %>%  # 80% trian set 
  pull(check_in_date)

train <- city_hotel %>% 
  filter(!check_in_date %in% training_dates)

test <- city_hotel %>% 
  filter(check_in_date %in% training_dates)
```

```{r}
numeric_vars <- hotels %>% 
  select_if(is.numeric) 
  
min_ <- map_df(numeric_vars, min, na.rm = TRUE)
mean_ <- map_df(numeric_vars, mean, na.rm = TRUE)
median_ <- map_df(numeric_vars, median, na.rm = TRUE)
sd_ <- map_df(numeric_vars, sd, na.rm = TRUE)
max_ <- map_df(numeric_vars, max, na.rm = TRUE)


b <- bind_rows(min_, mean_, median_, sd_, max_) 

table <- bind_cols(tibble(" " = c("Minimum", "Mean", "Median", "Standard deviation", "Max")), b) %>% 
  mutate_if(is.numeric, round, 2) %>% 
  relocate(not_canceled, .after = is_canceled) %>% 
  rename_with(~str_replace_all(str_to_title(.x), "_", " ")) %>%
  clipr::write_clip()
```

```{r}
  
 cat_vars <- hotels %>% 
  select_if(is.character) 

cat_vars %>% 
  group_by(customer_type, deposit) %>% 
  tally() %>% 
  arrange(desc(n)) %>% 
  rename_with(~str_replace_all(str_to_title(.x), "_", " ")) %>% 
  mutate(N = prettyNum(N, big.mark = ",")) %>% 
  clipr::write_clip()

  
```


```{r}
logistic_fit <- glm(not_canceled ~ 
                      adults + 
                      children + 
                      babies + 
                      lead_time + 
                      stay_length + 
                      customer_type +
                      deposit, data = train,
                      family = binomial(link = logit))

# logistic_fit1 <- glm(not_canceled ~ 
#                       adults + 
#                       children + 
#                       babies + 
#                       lead_time + 
#                       stay_length, data = train,
#                       family = binomial(link = logit))
# 
# logistic_fit2 <- glm(not_canceled ~ 
#                       adults + 
#                       children + 
#                       babies, data = train,
#                       family = binomial(link = logit))
# 
# 
# stargazer::stargazer(logistic_fit,logistic_fit1,logistic_fit2, type = 'html',
#                      dep.var.labels = "Log Odds of Arrival",
#                      covariate.labels = c(
#                                           "Adults", "Children",
#                                           "Babies", "Lead Time (Days)",
#                                           "Stay Length (Days)",
#                                           "Customer Type: Group",
#                                           "Customer Type: Transient",
#                                           "Customer Type: Tranient-Party",
#                                           "No Deposit")
#                       ) %>%
#   clipr::write_clip()
```

```{r}
capacity_frac <- function (p, rooms=100, loss=4, min_p=0.065) {
E <- 0; E_m1 <- 0; Fx <- 0;
P_overbook <- 0; bookings <- rooms;

  if(p > min_p) {
    while(E_m1 >= E) {
      E <-  bookings * Fx - loss * (bookings - rooms) * P_overbook
      Fx <-  pbinom(rooms, bookings, p, lower.tail = TRUE)
      bookings <-  bookings + 1
      P_overbook <-  1 - Fx
      E_m1 <-  bookings * Fx - loss * (bookings - rooms) * P_overbook
      }
  } else {
    bookings = rooms * 10
  }
  return(bookings)
}

```

```{r}
test_pred <- test %>% 
  mutate(p_hat = predict(logistic_fit, 
                         newdata = test, type = "response"),
         cap = map_dbl(p_hat, capacity_frac),
         cap_fra = 1/cap) 
```

```{r}
sample_fn_overbook <- function(data_input, p_threash = 0.99) {
  
  success <- FALSE; i <- 1; samp <- data_input[1,]
  while(!success) {
    samp[i,] <- slice_sample(data_input, n = 1)
    success <- sum(samp$cap_fra) > p_threash
    i <- i + 1
  }
  samp <- samp[1:i,]
  
  return(samp)
}
```

```{r}
sample_capacity <- function(data_input, capacity = 100) {
  output <- slice_sample(data_input, n = capacity, replace = TRUE)
  return(output)
}
```

```{r}
sample_same_phat <- function(data_input, capacity = 100) {
  output <- slice_sample(data_input, n = 129, replace = TRUE)
  return(output)
}
```


```{r}
simulater <- function (x) {
  message(paste0(x))
 test_pred %>%
  group_by(check_in_date) %>% 
  nest() %>%
  mutate(
         resampled_overbookings = map(data, sample_fn_overbook),
         resampled_same_phat = map(data, sample_same_phat),
         resampled_capacity = map(data, sample_capacity),
         
         over_nbookings = map_dbl(resampled_overbookings, ~nrow(.x)),
         over_canceled = map_dbl(resampled_overbookings, ~sum(.x$is_canceled, na.rm = TRUE)),
         over_booking_arrivals = over_nbookings - over_canceled,
         
         over_same_phat = map_dbl(resampled_same_phat, ~nrow(.x)),
         over_canceled_same_p = map_dbl(resampled_same_phat, ~sum(.x$is_canceled, na.rm = TRUE)),
         over_same_phat_arrivals = over_nbookings - over_canceled_same_p,
         
         booking_n = map_dbl(resampled_capacity, ~nrow(.x)),
         booking_canceled = map_dbl(resampled_capacity, ~sum(.x$is_canceled, na.rm = TRUE)),
         booking_arrivals = booking_n - booking_canceled,
         
         iter = x
         )   %>%
  select_if(is.numeric)
}
```


```{r}
tic()
sim_iters <- map(1:2, simulater) %>% 
  bind_rows()
toc()

sim_iters %>% 
    select_if(is.numeric) %>% 
write.csv(here::here("data", "sim_results_iterations.csv"))
```


```{r}
sim_results <- here::here("data", "sim_results_iterations.csv") %>% 
   readr::read_csv() %>% 
  mutate(over_booking_arrivals_phat = over_nbookings - over_canceled_same_p) %>% 
  rename(over_same_phat_arrivals = over_booking_arrivals_phat)
```


```{r}
sim_results %>% 
  ggplot(aes(x = check_in_date, y = over_booking_arrivals)) + 
  stat_bin2d(aes(fill = after_stat(count)), binwidth = c(1,1)) +
  geom_hline(yintercept = 100, color = "red") + 
  labs(x = "Booking Results", y = "Number of Arrivals") + 
  scale_fill_viridis_c()
```

```{r}
library(forcats)
sim <- sim_results %>% 
  select(check_in_date,over_booking_arrivals, over_same_phat_arrivals, booking_arrivals) %>% 
  pivot_longer(cols = over_booking_arrivals:booking_arrivals, names_to = "strategy", values_to = "arrivals") %>%
  mutate(strat_name = case_when(
                                strategy == "over_booking_arrivals"   ~ "Proposed Overbooking Strategy",
                                strategy == "over_same_phat_arrivals" ~ "Overbooking with Constant P",
                                strategy == "booking_arrivals"        ~ "Booking at Capacity",
                                ),
         strat_name = fct_relevel(strat_name,
                                     "Proposed Overbooking Strategy",
                                     "Overbooking with Constant P",
                                     "Booking at Capacity"
                                     ))
```

```{r}
sim_summary <- sim %>% 
  group_by(check_in_date, strat_name) %>% 
  summarise(mean = mean(arrivals),
            x_05 = quantile(arrivals, 0.05),
            x_95 = quantile(arrivals, 0.95),
            )
```


```{r}
points <- ggplot(data = sim) + 
    geom_point(aes(x = check_in_date, y = arrivals), color = "grey85", alpha = 0.1) 
```

```{r}
points
```

```{r}
stat_lines <- points + 
    # stat_bin2d(aes(fill = after_stat(count)), binwidth = c(1,1)) +
    geom_line(data = sim_summary, aes(x = check_in_date, y = mean),
              color = "black") + 
    geom_line(data = sim_summary, aes(x = check_in_date, y = x_95),
              color = "grey30", linetype = "dashed", alpha = .9) + 
    geom_line(data = sim_summary, aes(x = check_in_date, y = x_05), 
              color = "grey30", linetype = "dashed", alpha = .9)
```

```{r}
stat_lines
```

```{r}
stat_lines +
    geom_hline(yintercept = 100, color = "red") + 
    labs(x = "Booking Results", y = "Number of Arrivals", fill = "Frequency") + 
    scale_fill_viridis_c(option = "B") + 
    facet_wrap(~strat_name, ncol = 1, scales = "free") + 
    theme_bw()

ggsave(here::here("R","figures", "Figure_sim_test.png"),
       height = 11, width = 8.5)
```

```{r}
ggsave(here::here("R","figures", "Figure_sim_test.png"),
       height = 11, width = 8.5)
```



